In [25]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

### 1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [26]:
type(list_)

list

In [27]:
type(array_list)

numpy.ndarray

<br>
<br>

### 2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [28]:
list(map(lambda i:type(i),list_))

[str, str, str, str, str]

In [29]:
array_list.dtype

dtype('<U1')

<br>
<br>

### 3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [30]:
array_list = np.array(object = list_, dtype = int)

In [31]:
array_list

array([1, 2, 3, 4, 5])

In [32]:
array_list.dtype

dtype('int64')

===========================xx=========================

In [33]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

<br>
<br>

### 4. Write a code to find the following characteristics of variable, num_array:
(i) shape <br>
(ii) size

In [34]:
num_array.shape

(2, 3)

In [35]:
num_array.size

6

<br>
<br>

### 5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [36]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

<br>
<br>

### 6. Create an identity matrix of shape (5,5) using numpy functions?

In [37]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])